# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
pool:
  name: Hosted VS2017
  demands: npm

name: 1.0.$(BuildID)
steps:
- powershell: |
   $branchName = "$Env:Build_SourceBranchName"
   
   # Empty name when branch is master
   if ($branchName -eq "master"){
       $branchName = ""
   } else {
       $branchName = "-$branchName";
   }
   
   $versionNumber = "$Env:Build_BuildNumber$branchName";
   Write-Host "Calculated version: $versionNumber"
   
   # Setting variable
   Write-Host "##vso[task.setvariable variable=versionNumber;isOutput=true]$versionNumber"

  displayName: 'Calculate version'
  name: calculateVersion

- task: Npm@1
  displayName: 'npm version'
  inputs:
    command: custom
    verbose: false
    customCommand: 'version $(calculateVersion.versionNumber) --no-git-tag-version'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'Build app'

- script: |
    npm run lint
  displayName: 'Run JS Linting'

- script: |
    npm run test 
  displayName: 'Run unit test'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: xUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)/*test-results.xml'
  displayName: 'Publish TestResults'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/test-coverage'
  displayName: 'Publish Code Coverage Results'

- task: Npm@1
  inputs:
    command: publish
    publishEndpoint: 'NpmRegistry'
#  
#  condition: eq(variables['Build.SourceBranchName'], 'master')
