# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'Build app'

- script: |
    npm run lint
  displayName: 'Run JS Linting'

- script: |
    npm run test 
  displayName: 'Run unit test'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: xUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)/*test-results.xml'
  displayName: 'Publish TestResults'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/test-coverage'
  displayName: 'Publish Code Coverage Results'